### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Pari-Malam/RTSP-FindingSomeFun#1]
```
[RTSP] - Perform With RTSP Scanner & Brute Force

[Output Filename]: list.txt
[IP/URL List]: rtsp://192.168.0.91:554
[ERROR!] - Bro? Whutt are you doin?rtsp://192.168.0.91:554
Traceback (most recent call last):
  File "rtsp.py", line 93, in main
    with open(target_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'rtsp://192.168.0.91:554'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rtsp.py", line 112, in <module>
    main()
  File "rtsp.py", line 97, in main
    sys.exit(1)
NameError: name 'sys' is not defined

```

and 
```
[RTSP] - Perform With RTSP Scanner & Brute Force

[Output Filename]: list.txt
[IP/URL List]: 192.168.0.91
[ERROR!] - Bro? Whutt are you doin?192.168.0.91
Traceback (most recent call last):
  File "rtsp.py", line 93, in main
    with open(target_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'rtsp://192.168.0.91:554'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rtsp.py", line 112, in <module>
    main()
  File "rtsp.py", line 97, in main
    sys.exit(1)
NameError: name 'sys' is not defined

```
and 
```
[RTSP] - Perform With RTSP Scanner & Brute Force

[Output Filename]: list.txt
[IP/URL List]: 192.168.0.1/24
[ERROR!] - Bro? Whutt are you doin?192.168.0.1/24
Traceback (most recent call last):
  File "rtsp.py", line 93, in main
    with open(target_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'rtsp://192.168.0.91:554'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rtsp.py", line 112, in <module>
    main()
  File "rtsp.py", line 97, in main
    sys.exit(1)
NameError: name 'sys' is not defined
```

**Comment by Ap0dexMe0** [comment]
> ```
> [RTSP] - Perform With RTSP Scanner & Brute Force
> 
> [Output Filename]: list.txt
> [IP/URL List]: rtsp://192.168.0.91:554
> [ERROR!] - Bro? Whutt are you doin?rtsp://192.168.0.91:554
> Traceback (most recent call last):
>   File "rtsp.py", line 93, in main
>     with open(target_file, "r") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'rtsp://192.168.0.91:554'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "rtsp.py", line 112, in <module>
>     main()
>   File "rtsp.py", line 97, in main
>     sys.exit(1)
> NameError: name 'sys' is not defined
> ```
> 
> and
> 
> ```
> [RTSP] - Perform With RTSP Scanner & Brute Force
> 
> [Output Filename]: list.txt
> [IP/URL List]: 192.168.0.91
> [ERROR!] - Bro? Whutt are you doin?192.168.0.91
> Traceback (most recent call last):
>   File "rtsp.py", line 93, in main
>     with open(target_file, "r") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'rtsp://192.168.0.91:554'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "rtsp.py", line 112, in <module>
>     main()
>   File "rtsp.py", line 97, in main
>     sys.exit(1)
> NameError: name 'sys' is not defined
> ```
> 
> and
> 
> ```
> [RTSP] - Perform With RTSP Scanner & Brute Force
> 
> [Output Filename]: list.txt
> [IP/URL List]: 192.168.0.1/24
> [ERROR!] - Bro? Whutt are you doin?192.168.0.1/24
> Traceback (most recent call last):
>   File "rtsp.py", line 93, in main
>     with open(target_file, "r") as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'rtsp://192.168.0.91:554'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "rtsp.py", line 112, in <module>
>     main()
>   File "rtsp.py", line 97, in main
>     sys.exit(1)
> NameError: name 'sys' is not defined
> ```

pull request
